/**
 * A blank Cursor subagent file. Field values stay empty or use safe defaults.
 * Comments tell the author what to type. They are not instructions for the model
 * until the author replaces them.
 */
export function emptyAgentMarkdown(slug: string, displayName: string): string {
  return [
    "---",
    `# name: slug you type after / in chat. This file is called with /${slug}. Use lowercase letters, numbers, and hyphens.`,
    `name: ${slug}`,
    "# description: one sentence Cursor uses to decide when to delegate to this agent. Replace the placeholder.",
    'description: "Describe when to use this agent."',
    "# model: inherit uses the parent chat model. Or set a model id such as composer-2.5. Optional parameters use model[id=value].",
    "model: inherit",
    "# readonly: true blocks edits and state-changing shell commands. false lets this agent change files.",
    "readonly: false",
    "# is_background: true runs without blocking the chat. Leave false when an orchestra must wait for this agent.",
    "is_background: false",
    "---",
    "",
    `# ${displayName}`,
    "",
    "<!-- Role: replace this comment with one short paragraph. Who this agent is, and what it specializes in. -->",
    "",
    "<!-- Instructions: replace this comment with how the agent should work. Include the order of steps and what it must not do. -->",
    "",
    "## Responsibilities",
    "",
    "<!-- One bullet per job this agent owns. Example: - Review the diff for regressions -->",
    "",
    "## Constraints",
    "",
    "<!-- One bullet per boundary. Example: - Do not change public APIs -->",
    "",
    "## Context",
    "",
    "<!-- Paths to read before changing anything. Examples:",
    "- file: `src/example.ts`",
    "- folder: `src/`",
    "-->",
    "",
    "## Project rules",
    "",
    "<!-- Conventions from this repository that this agent must follow. Workspace rules still apply separately. -->",
    "",
    "## Behavior",
    "",
    "<!-- How to approach the work. Example: make the smallest change and verify before reporting done. -->",
    "",
    "## Output",
    "",
    "<!-- What to return: format, order, and what counts as done. -->",
    "",
    "## Skills",
    "",
    "<!-- Skills this agent should use. Delete this comment when none apply. -->",
    "",
  ].join("\n");
}
